# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # this hook lets us avoid sending yubikey messages when other hooks fail
  - repo: local
    hooks:
      - id: cleaner
        name: cleaner
        entry: bash .github/clean-precommit.sh
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        log_file: pre-commit.log
      - id: end-of-file-fixer
        exclude: .idea|\.yml.enc$
        log_file: pre-commit.log
      - id: check-added-large-files
        args:
          - "--maxkb=5000"
        log_file: pre-commit.log
      - id: check-merge-conflict
        log_file: pre-commit.log
      - id: check-symlinks
        log_file: pre-commit.log

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        log_file: pre-commit.log

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        log_file: pre-commit.log

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - "--no-warnings"
          - "-c=.yamllint-config.yaml"
        log_file: pre-commit.log

  - repo: https://github.com/rubocop/rubocop
    rev: v1.57.2
    hooks:
      - id: rubocop
        language: system
        entry: rubocop -c .rubocop.yml -a --fail-level E
        log_file: pre-commit.log

  - repo: local
    hooks:
      - id: ruff
        name: ruff linting for python
        language: system
        entry: uv run ruff check --fix -q
        files: \.py$|pyproject.toml|uv.lock
        verbose: true
        pass_filenames: false
        log_file: pre-commit.log
      - id: ruff
        name: ruff formatting for python
        language: system
        entry: uv run ruff format -q
        files: \.py$|pyproject.toml|uv.lock
        verbose: true
        pass_filenames: false
        log_file: pre-commit.log
      - id: mypy
        name: MyPy Type Validation
        language: system
        entry: uv run mypy --no-color-output --no-error-summary .
        files: \.py$|pyproject.toml|uv.lock
        pass_filenames: false
        verbose: true
        log_file: pre-commit.log

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args:
          - "--shell=bash"
          - "-x"
        log_file: pre-commit.log

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1  # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        log_file: pre-commit.log

  - repo: local
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: markdownlint -c .markdownlint.json --fix
        language: system
        files: \.(md|mdown|markdown)$
        verbose: true
        log_file: pre-commit.log
      - id: actionlint
        name: Github Actions Linting
        entry: actionlint
        language: system
        files: .github/workflows
        verbose: true
        log_file: pre-commit.log

  # security scans
  - repo: local
    hooks:
      - id: trufflehog
        name: Trufflehog Scan
        entry: env TRUFFLE_ONLY=true scripts/utils/security.sh
        pass_filenames: false
        language: system
        verbose: true
